### ISSUE TITLE
Support to download the check_mk git repo to the Ansible controller

### ISSUE THREAD

**Issue by ypid** [debops-contrib/ansible-checkmk_agent#29]
I think it would make sense to make it configurable whether the git repo is cloned to all remote hosts separately or to the Ansible controller (currently not supported).

What do you think? Last time a checked the repo was 569 MiB which can sum up depending on the size of the cluster (and that just to install a few agent plugins).

Ref: https://github.com/debops-contrib/ansible-checkmk_agent/blob/master/tasks/setup_plugins.yml

**Comment by drybjed** [comment]
I briefly looked if cloning directly from a local directory to a remote host is feasible, it looks like [using git remote is a sensible option](https://stackoverflow.com/questions/4142936/git-clone-from-local-to-remote) but I don't think that `git` Ansible module supports that. To do a clone from Ansible Controller directly would probably require at least a few `command` tasks to setup everything.

Perhaps a better alternative is to setup a local GitLab service, create a clone of the `check_mk` git repository there and periodically pull new commits. Users could then point the role to their local Gitlab instance and offload the transfer that way.

**Comment by ypid** [comment]
I had a simple `copy` task in mind to copy over the needed agent plugins. Currently the same is done using syncronize but from the remote host to itself. Only difference would be that the plugin is copied from the controller.

**Comment by ganto** [comment]
> I think it would make sense to make it configurable whether the git repo is cloned to all remote hosts separately or to the Ansible controller (currently not supported).

Sounds like a good plan to me. Go for it 👍
