### ISSUE TITLE
debops integration

### ISSUE THREAD

**Issue by erikschwalbe** [debops-contrib/ansible-checkmk_agent#32]
Hi,

I installed debops on /home/ansible/debops and it works like a charm.
Try to add debops-contrib:
`ansible-galaxy install debops-contrib.checkmk_agent`
`-extracting debops-contrib.checkmk_agent to /home/ansible/.ansible/roles/debops-contrib.checkmk_agent`
`-debops-contrib.checkmk_agent (v0.1.1) was installed successfully`
But if I add the host to [debops_service**s**_checkmk_agent] in inventory/hosts nothing happens
Is it possible only to execute the role like other debops services: eg. debops service/apache -l host

Is there somthing wrong?

Thanks for help
Regards,
Erik

**Comment by ganto** [comment]
Thanks a lot for your interest in this role. As this role is not officially supported by the DebOps maintainers, it's not added to the default playbook executed when you're running `debops`.

To run this role, you have to define the host group in the inventory (btw. there is a inconsistency between the playbook and the docs, the playbooks requires `debops_service_checkmk_agent`) and then give the playbook from the role as argument:
```
debops /home/ansible/.ansible/roles/debops-contrib.checkmk_agent/doc/playbooks/checkmk_agent.yml

**Comment by erikschwalbe** [comment]
ok thanks then it was a typo in [documentation](https://debops-contrib.readthedocs.io/en/latest/ansible/roles/ansible-checkmk_agent/docs/getting-started.html).

Regards,
Erik
